<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>


    <parent>
        <groupId>com.activity-master</groupId>
        <artifactId>activitymaster-group</artifactId>
        <version>3.0.0-SNAPSHOT</version>
    </parent>

     <groupId>com.activity-master</groupId>
    <artifactId>session-master</artifactId>
    <name>Session Master</name>
    <packaging>jar</packaging>
    <properties>
        <project.scm.nameUrl>/Activity-Master/SessionMaster</project.scm.nameUrl>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-sql-client</artifactId>
        </dependency>


        <dependency>
            <groupId>com.activity-master</groupId>
            <artifactId>activity-master</artifactId>
        </dependency>

        <dependency>
            <groupId>com.activity-master</groupId>
            <artifactId>profile-master</artifactId>
        </dependency>

        <dependency>
            <groupId>com.guicedee.modules.representations</groupId>
            <artifactId>json-representation</artifactId>
        </dependency>

        <dependency>
            <groupId>com.guicedee.modules.services</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>

        <dependency>
            <groupId>com.guicedee.modules.services</groupId>
            <artifactId>testcontainers</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <compilerArgs>
                        <arg>--add-reads</arg>
                        <arg>org.jboss.logging=org.hibernate.reactive</arg>
                        <arg>--add-reads</arg>
                        <arg>org.hibernate.orm.core=com.guicedee.activitymaster.fsdm</arg>
                    </compilerArgs>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>
                        --add-reads org.jboss.logging=org.hibernate.reactive
                        --add-reads org.hibernate.orm.core=com.guicedee.activitymaster.fsdm
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
